name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  lint:
    name: CI
    uses: TytaniumDev/.github/.github/workflows/lint.yml@main

  build:
    name: CI
    uses: TytaniumDev/.github/.github/workflows/build.yml@main

  test:
    name: CI
    uses: TytaniumDev/.github/.github/workflows/test.yml@main
